--Table 1: users (for admin & customers)--

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL,  
    phone VARCHAR2(20),
    address VARCHAR2(200),
    is_admin NUMBER(1) DEFAULT 0,  -- 0 = customer, 1 = admin
    created_date DATE DEFAULT SYSDATE
);

CREATE TABLE menu_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(300),
    price NUMBER(8,2) NOT NULL,
    image_path VARCHAR2(200),  -- just store filename
    is_available NUMBER(1) DEFAULT 1  -- 1 = yes, 0 = no
);

CREATE TABLE cart (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    item_id NUMBER REFERENCES menu_items(id),
    quantity NUMBER DEFAULT 1,
    added_date DATE DEFAULT SYSDATE
);

CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES users(id),
    total_price NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'Pending',
    order_date DATE DEFAULT SYSDATE,
    delivery_address VARCHAR2(200)
);

-- Create ORDER_ITEMS table if it doesn't exist
CREATE TABLE ORDER_ITEMS (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id NUMBER REFERENCES ORDERS(id),
    item_id NUMBER REFERENCES MENU_ITEMS(id),
    item_name VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    price NUMBER(8,2) NOT NULL,
    total NUMBER(10,2) NOT NULL
);

------for making you as andmin-----
-- Update hatim@gmail.com to be an admin
UPDATE users 
SET is_admin = 1 
WHERE email = 'hatim@gmail.com';

COMMIT;

-- Verify the update
SELECT username, email, is_admin FROM users WHERE email = 'hatim@gmail.com';

